config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  devise_for :users 
  
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :projects
  
  resources :posts do 
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :comment_body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :content_body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :comments, dependent: :destroy 

      
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  helper_method [:is_admin?, :is_creator?]

  def is_admin?
    current_user && current_user.admin
  end

  def is_creator?
    Comment.find(params[:id]).user == current_user

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:new]
  before_action :only => [:edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end


  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
    render :new
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    render :show
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    render :edit
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end


  private
    def comment_params
      params.require(:comment).permit(:author, :comment_body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :only => [:new, :edit] do 
    unless is_admin?
      flash[:alert] = 'You do not have access to this content.'
      redirect_to posts_path 
      end
  end

  def require_admin
    if !current_user.admin?
      redirect_to benefits_path
    end
  end

  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def update
    @post= Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user.admin?
      @post.destroy
    else
      flash[:alert] = 'You do not have access to this content.'
    end
    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:subject, :content_body)
    end

  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action except: [:index, :show] do 
    unless is_admin?
      flash[:alert] = 'You do not have access to this content.'
      redirect_to projects_path 
      end
  end
  
  def index
    @projects = Project.all
    render :index
  end

  def new
    @roject = Project.new
    render :new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    render :edit
  end

  def show
    @project = Project.find(params[:id])
    render :show
  end

  def update
    @project= Project.find(params[:id])
    if @projec.update(projec_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private
    def project_params
      params.require(:post).permit(:name, :author)
    end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h1>edit a comment:</h1>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :comment_body %>
  <%= f.text_area :comment_body %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/new.html.erb
<h1>add a comment:</h1>


<%= form_for [@post, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :comment_body %>
  <%= f.text_area :comment_body %>

  <p><%= f.submit %></p>
<% end %>

app/views/comments/show.html.erb
<h1>comment by: <%= @comment.author %></h1>
<h2>Post subject: <%= @post.subject %></h2><br><br>
<h4><%= @comment.comment_body %></h4>

<p><%= link_to "Edit comment", edit_post_comment_path(@post, @comment) %></p>
<p><%= link_to "Delete comment", post_comment_path(@post, @comment),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to postings", post_path(@post) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CMSSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>edit posting</h1>

<%= form_for @post do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body  %>
  <%= f.submit  %>
<% end %>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <ul>
    <% @posts.each do |post| %>
      <li><%= link_to post.subject, post_path(post) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No posts yet.</p>
<% end %>


<p><%= link_to "add post", new_post_path %></p>

<p><%= link_to "return to projects", projects_path %></p>

<p><%= link_to "add user", projects_path %></p>

app/views/posts/new.html.erb
<h1>create a new posting</h1>


<%= form_for @post do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.submit  %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.subject %></h1>
<h4><%= @post.content_body %></h4>

<% if @post.comments.any? %>
  <h4>Comments:</h4>

  <% @post.comments.each do |comment| %>
    <ul>
      <li>
        <%= link_to comment.author, post_comment_path(@post, comment) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No comments yet for this posting, check back soon.</p>
<% end %>

<p><%= link_to "Add a comment", new_post_comment_path(@post) %></p>

<p><%= link_to "Edit", edit_post_path(@post) %></p>
<p><%= link_to "Delete", post_path(@post),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "return to postings", posts_path %></p>

app/views/projects/index.html.erb
<% if @projects.any? %>
  <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project.name, project_path(project) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No projects.</p>
<% end %>




<p><%= link_to "view posts", posts_path %></p>

<p><%= link_to "sign up", new_user_registration_path %></p>




<p><%= link_to "sign in", user_session_path%></p>

<p><%= link_to "sign out", destroy_user_session_path%></p>

app/views/projects/new.html.erb
<h1>new project</h1>

<%= link_to 'return to projects', projects_path %>